/** Shared storage, WAL and payload context for the internal delegation modules. */
import * as fs from "node:fs/promises";
import * as nodeFs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";
import { getAgentDiscoverySnapshot, validAgentDiscoverySnapshot, type AgentDiscoverySnapshot, type AgentScope } from "./agents.ts";
import { lineageMatches, type ActiveLineage } from "./lineage.ts";
import { withIdentityLock } from "./session-lock.ts";
import { atomicOwnerJson, ensureOwnerDirectory, openOwnerFile, ownerFileSync, syncDirectory, readStableOwnerFileSync } from "./secure-fs.ts";
import { appendRecords, assertTransition, hasQuarantinedWal, makeEvent, quarantineWal, readWal, replay, validateWalEvent, WalCorruption, type WalAppendOptions, type WalReplayContext } from "./wal-replay.ts";
import type { ConfigRevisionActor, DelegationFoundationDependencies, DispatchCallAdmissionRequest, DispatchCallView, DispatchItemInput, InternalDelegation, InternalView, ProjectTrustBinding, RevisionIntent, RevisionLifecycle, RevisionObservation, TornTail, WalEvent } from "./delegation-types.ts";
import type { CanonicalProvenance } from "./resolver.ts";

export const V2_ROOT = "v2";
export const OWNER_ONLY_FILE = 0o600;
export class WalAppendGuardRejected extends Error {
  constructor() { super("WAL append guard rejected the write"); this.name = "WalAppendGuardRejected"; }
}
export function hash(value: string | Buffer): string { return createHash("sha256").update(value).digest("hex"); }
export function hashPath(value: string): string { return hash(path.resolve(value)).slice(0, 32); }
export function toolCallHash(value: string): string { return hash(value); }
export function dirs(rootDir: string) { const root = path.join(rootDir, V2_ROOT); return { root, wal: path.join(root, "wal"), calls: path.join(root, "calls"), delegations: path.join(root, "delegations"), private: path.join(root, "private"), proofs: path.join(root, "proofs") }; }
export function callWal(d: ReturnType<typeof dirs>, callId: string): string { return path.join(d.wal, `${callId}.jsonl`); }
export function callProjection(d: ReturnType<typeof dirs>, callId: string): string { return path.join(d.calls, `${callId}.json`); }
export function delegationProjection(d: ReturnType<typeof dirs>, id: string): string { return path.join(d.delegations, `${id}.json`); }
export function privatePayload(d: ReturnType<typeof dirs>, id: string): string { return path.join(d.private, `${id}.json`); }
export function proofPath(d: ReturnType<typeof dirs>, id: string): string { return path.join(d.proofs, `${id}.json`); }
export async function ensureDirectory(directory: string): Promise<void> { await ensureOwnerDirectory(directory); }
export async function ensureStore(rootDir: string) { const d = dirs(rootDir); for (const directory of [d.root, d.wal, d.calls, d.delegations, d.private, d.proofs]) await ensureDirectory(directory); return d; }
export async function openSecureFile(file: string, flags: number, mode = OWNER_ONLY_FILE): Promise<fs.FileHandle> { return openOwnerFile(file, flags, mode); }
export async function atomicJson(file: string, value: unknown): Promise<void> { return atomicOwnerJson(file, value); }
export async function writePrivate(file: string, value: unknown): Promise<void> { await atomicJson(file, value); }
export async function readPrivate<T>(file: string): Promise<T> { const handle = await openSecureFile(file, nodeFs.constants.O_RDONLY); try { return JSON.parse(await handle.readFile("utf8")) as T; } finally { await handle.close(); } }

export function exactObject(value: unknown, required: string[], optional: string[] = []): value is Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const keys = Object.keys(value); return required.every((key) => keys.includes(key)) && keys.every((key) => required.includes(key) || optional.includes(key)); }
export function isHex(value: unknown, length = 64): value is string { return typeof value === "string" && new RegExp(`^[0-9a-f]{${length}}$`).test(value); }
export function validResultRef(value: unknown): value is string { return typeof value === "string" && value.length <= 128 && (value.length === 0 || /^[A-Za-z0-9._:-]+$/.test(value)); }

function revisionIdFor(delegationId: string, epoch: number): string { return `${delegationId}:r${epoch}`; }
function revisionRef(delegationId: string, epoch: number): string { return `private:revision-${delegationId}-${epoch}`; }
function maxRevisionEpoch(view: InternalView, delegationId: string): number { return view.events.filter((event) => event.delegationId === delegationId && (["delegation_configuration_observed", "delegation_configuration_observation_superseded", "config_revision_accepted"].includes(event.type) || event.type === "delegation_paused" && event.data.reason === "configuration revision pending")).reduce((max, event) => Math.max(max, Number(event.data.revisionEpoch) || 0), 0); }
function sameRevisionActor(a: ConfigRevisionActor, b: ConfigRevisionActor): boolean { return a.actorId === b.actorId && a.parentSessionId === b.parentSessionId && a.activeLineageId === b.activeLineageId && a.activeBranchAnchor === b.activeBranchAnchor; }
function sameRevisionIntent(a: RevisionIntent, b: RevisionIntent): boolean { return a.revisionId === b.revisionId && a.revisionEpoch === b.revisionEpoch && a.oldDigest === b.oldDigest && a.newDigest === b.newDigest && sameRevisionActor(a.actor, b.actor); }
const WAL_CONTEXT: WalReplayContext = {
  delegationIdFor: (callId, index) => hash(JSON.stringify(["delegation-v3", callId, index])),
  eventDelegationIdMatches: (call, delegationId, slotIndex) => slotIndex >= 0 && !!call.slots[slotIndex] && delegationId === hash(JSON.stringify(["delegation-v3", call.dispatchCallId, slotIndex])),
  revisionIdFor, revisionRef, maxRevisionEpoch, sameRevisionActor, sameRevisionIntent,
  validOwnerIdentity: (value): value is import("./delegation-types.ts").OwnerIdentity => {
    if (!value || typeof value !== "object" || Array.isArray(value)) return false; const owner = value as Record<string, unknown>;
    return Object.keys(owner).length === 6 && typeof owner.host === "string" && owner.host.length > 0 && Number.isSafeInteger(owner.pid) && Number(owner.pid) > 0 && typeof owner.birth === "string" && owner.birth.length > 0 && typeof owner.parentSessionId === "string" && owner.parentSessionId.length > 0 && typeof owner.parentSessionPath === "string" && path.isAbsolute(owner.parentSessionPath) && typeof owner.argvProof === "string" && /^[0-9a-f]{64}$/.test(owner.argvProof);
  },
};
export { WAL_CONTEXT };

async function repairTailAndAudit(rootDir: string, callId: string, tail: TornTail): Promise<void> {
  const d = dirs(rootDir); const file = callWal(d, callId); const loaded = await readWal(file, WAL_CONTEXT); const previous = loaded.events.at(-1); const audit = makeEvent(callId, (previous?.seq ?? 0) + 1, previous?.checksum ?? "", "wal_torn_tail_repaired", { discardedBytes: tail.discardedBytes, tailHash: tail.tailHash });
  try { const current = loaded.events.length === 0 ? { delegations: new Map(), revisionLifecycles: new Map(), events: [] } as InternalView : replay(loaded.events, callId, WAL_CONTEXT); validateWalEvent(audit, callId, WAL_CONTEXT); assertTransition(current, audit.type, audit.delegationId, audit.data, WAL_CONTEXT); } catch (error) { await quarantineWal(file).catch(() => undefined); throw error; }
  const handle = await openSecureFile(file, nodeFs.constants.O_RDWR); try { const content = await handle.readFile("utf8"); const newline = content.lastIndexOf("\n"); await handle.truncate(newline < 0 ? 0 : Buffer.byteLength(content.slice(0, newline + 1))); await handle.sync(); } finally { await handle.close(); }
  await syncDirectory(d.wal); await appendRecords(file, [audit]);
}
export async function appendWal(rootDir: string, callId: string, type: string, data: Record<string, unknown>, delegationId: string | undefined, deps?: DelegationFoundationDependencies, options?: WalAppendOptions): Promise<void> {
  const d = await ensureStore(rootDir); const file = callWal(d, callId); if (await hasQuarantinedWal(file)) throw new WalCorruption("WAL is quarantined"); let loaded = await readWal(file, WAL_CONTEXT); if (loaded.tornTail) { await repairTailAndAudit(rootDir, callId, loaded.tornTail); loaded = await readWal(file, WAL_CONTEXT); }
  const previous = loaded.events.at(-1); const event = makeEvent(callId, (previous?.seq ?? 0) + 1, previous?.checksum ?? "", type, data, delegationId); validateWalEvent(event, callId, WAL_CONTEXT); const current = loaded.events.length === 0 ? { delegations: new Map(), revisionLifecycles: new Map(), events: [] } as InternalView : replay(loaded.events, callId, WAL_CONTEXT); assertTransition(current, type, delegationId, data, WAL_CONTEXT);
  await deps?.fault?.(`before:${type}`); await appendRecords(file, [event], options); await deps?.fault?.(`after:${type}`);
}

export async function loadView(rootDir: string, callId: string): Promise<InternalView> {
  try { const d = await ensureStore(rootDir); const file = callWal(d, callId); if (await hasQuarantinedWal(file)) throw new WalCorruption("WAL is quarantined"); let loaded = await readWal(file, WAL_CONTEXT); if (loaded.missing) return { delegations: new Map(), revisionLifecycles: new Map(), events: [] }; if (loaded.tornTail) { await repairTailAndAudit(rootDir, callId, loaded.tornTail); loaded = await readWal(callWal(d, callId), WAL_CONTEXT); } return replay(loaded.events, callId, WAL_CONTEXT); }
  catch (error) { return { delegations: new Map(), revisionLifecycles: new Map(), events: [], integrity: { callId, reason: error instanceof Error ? error.message : "WAL integrity cannot be proven" } }; }
}
export async function loadViewForOwnerClaimPreflight(rootDir: string, callId: string): Promise<InternalView> {
  try { const d = await ensureStore(rootDir); const file = callWal(d, callId); if (await hasQuarantinedWal(file)) throw new WalCorruption("WAL is quarantined"); const loaded = await readWal(file, WAL_CONTEXT); if (loaded.missing) return { delegations: new Map(), revisionLifecycles: new Map(), events: [] }; const view = replay(loaded.events, callId, WAL_CONTEXT); if (loaded.tornTail) view.tornTail = loaded.tornTail; return view; }
  catch (error) { return { delegations: new Map(), revisionLifecycles: new Map(), events: [], integrity: { callId, reason: error instanceof Error ? error.message : "WAL integrity cannot be proven" } }; }
}
export async function materialize(rootDir: string, view: InternalView): Promise<void> {
  const d = dirs(rootDir);
  if (view.integrity) { await ensureDirectory(d.root); for (const directory of [d.calls, d.delegations, d.private, d.proofs]) await ensureDirectory(directory); await fs.unlink(proofPath(d, view.integrity.callId)).catch(() => undefined); await atomicJson(callProjection(d, view.integrity.callId), { version: 1, dispatchCallId: view.integrity.callId, state: "paused_integrity", reason: view.integrity.reason }); return; }
  await ensureStore(rootDir); if (!view.call) return;
  if (view.call.state === "repair_required") { await fs.unlink(callProjection(d, view.call.dispatchCallId)).catch(() => undefined); await fs.unlink(proofPath(d, view.call.dispatchCallId)).catch(() => undefined); for (const delegation of view.delegations.values()) await fs.unlink(delegationProjection(d, delegation.delegationId)).catch(() => undefined); return; }
  await atomicJson(callProjection(d, view.call.dispatchCallId), view.call);
  for (const delegation of view.delegations.values()) { const { requiredIdentity: _identity, provenanceRef: _provenance, ...publicDelegation } = delegation; await atomicJson(delegationProjection(d, delegation.delegationId), publicDelegation); }
  if (view.call.state === "final" && view.call.finalOutcome) { const proof = { version: 1 as const, dispatchCallId: view.call.dispatchCallId, mode: view.call.mode, slots: view.call.slots.slice().sort((a, b) => a.order - b.order).map(({ index, order, state, delegationId, terminalOutcome, resultRef }) => ({ index, order, state, ...(delegationId ? { delegationId } : {}), ...(terminalOutcome ? { terminalOutcome } : {}), ...(resultRef !== undefined ? { resultRef } : {}) })), outcome: view.call.finalOutcome, createdAt: String(view.events.find((event) => event.type === "call_admitted")?.data.createdAt ?? new Date().toISOString()), finalizedAt: String(view.events.find((event) => event.type === "call_finalized")?.data.finalizedAt ?? new Date().toISOString()) }; await atomicJson(proofPath(d, view.call.dispatchCallId), proof); }
}
export async function withCallLock<T>(rootDir: string, callId: string, fn: () => Promise<T>): Promise<T | undefined> { const d = dirs(rootDir); await ensureDirectory(d.root); for (let attempt = 0; attempt < 100; attempt += 1) { const result = await withIdentityLock({ rootDir: d.root, key: `call-${callId}` }, fn); if (result !== undefined) return result; await new Promise((resolve) => setTimeout(resolve, 5)); } return undefined; }
export async function withOrphanCoordination<T>(rootDir: string, fn: () => Promise<T>): Promise<T | undefined> { const d = await ensureStore(rootDir); return withIdentityLock({ rootDir: d.root, key: "private-orphan-reconcile" }, fn); }
export function pausedResult(callId: string, reason: string) { return { state: "paused_integrity" as const, dispatchCallId: callId, error: reason }; }

export function requestDigestFromParts(parentSessionId: string, lineage: ActiveLineage, toolCallId: string, cwd: string, mode: import("./delegation-types.ts").DispatchMode, items: DispatchItemInput[], agentScope: AgentScope, trust: ProjectTrustBinding | undefined, persistent: boolean | undefined): string { const normalizedItems = items.map((item) => ({ ...item, ...(item.cwd !== undefined ? { cwd: path.resolve(item.cwd) } : {}) })); return hash(JSON.stringify({ parentSessionId, lineage, toolCallId, cwd: path.resolve(cwd), mode, items: normalizedItems, agentScope, projectTrust: trust ?? null, persistent: persistent ?? null })); }
export function delegationPayloadDigest(payload: { delegationId: string; dispatchCallId: string; slotIndex: number; requiredIdentity: string; callRequestDigest: string; normalizedRequestDigest: string; effectiveCwd: string; projectRootRealpath?: string; projectSnapshotDigest?: string; projectSnapshot?: AgentDiscoverySnapshot; item: DispatchItemInput }): string { return hash(JSON.stringify({ delegationId: payload.delegationId, dispatchCallId: payload.dispatchCallId, slotIndex: payload.slotIndex, requiredIdentity: payload.requiredIdentity, callRequestDigest: payload.callRequestDigest, normalizedRequestDigest: payload.normalizedRequestDigest, effectiveCwd: path.resolve(payload.effectiveCwd), projectRootRealpath: payload.projectRootRealpath ?? null, projectSnapshotDigest: payload.projectSnapshotDigest ?? null, projectSnapshot: payload.projectSnapshot ?? null, item: payload.item })); }
export function safeTrustDigest(trust?: ProjectTrustBinding): string | undefined { return trust ? hash(JSON.stringify([trust.discoveryRootRealpath, trust.snapshotDigest])).slice(0, 32) : undefined; }
export function validProjectTrust(value: unknown, parentSessionId: string): value is ProjectTrustBinding { if (!exactObject(value, ["parentSessionId", "discoveryRootRealpath", "snapshotDigest"])) return false; const v = value as Record<string, unknown>; return v.parentSessionId === parentSessionId && typeof v.discoveryRootRealpath === "string" && path.isAbsolute(v.discoveryRootRealpath) && typeof v.snapshotDigest === "string" && v.snapshotDigest.length === 64; }

type CallPayload = { dispatchCallId: string; requestDigest: string; parentSessionId: string; lineage: ActiveLineage; toolCallId: string; mode: import("./delegation-types.ts").DispatchMode; items: DispatchItemInput[]; cwd: string; agentScope: AgentScope; persistent?: boolean; projectTrust?: ProjectTrustBinding; projectSnapshot?: AgentDiscoverySnapshot; projectRootRealpath?: string; projectSnapshotDigest?: string };
let revisionPrivateValidator: ((value: unknown, dispatchCallId: string, delegationId: string) => boolean) | undefined;
export function configureRevisionPrivateValidator(validator: (value: unknown, dispatchCallId: string, delegationId: string) => boolean): void { revisionPrivateValidator = validator; }
export async function callPayload(rootDir: string, view: DispatchCallView): Promise<CallPayload> { const d = dirs(rootDir); const payload = await readPrivate<CallPayload>(privatePayload(d, view.privatePayloadRef.slice(8))); const computed = requestDigestFromParts(payload.parentSessionId, payload.lineage, payload.toolCallId, payload.cwd, payload.mode, payload.items, payload.agentScope, payload.projectTrust, payload.persistent); if (payload.dispatchCallId !== view.dispatchCallId || computed !== payload.requestDigest || payload.requestDigest !== view.requestDigest || payload.parentSessionId !== view.parentSessionId || payload.lineage.activeLineageId !== view.activeLineageId || payload.lineage.activeBranchAnchor !== view.activeBranchAnchor || toolCallHash(payload.toolCallId) !== view.toolCallIdHash || payload.mode !== view.mode || payload.agentScope !== view.agentScope || safeTrustDigest(payload.projectTrust) !== view.projectTrustDigest || !Array.isArray(payload.items) || !path.isAbsolute(payload.cwd) || (payload.projectTrust && (!validProjectTrust(payload.projectTrust, payload.parentSessionId) || payload.projectRootRealpath !== payload.projectTrust.discoveryRootRealpath || payload.projectSnapshotDigest !== payload.projectTrust.snapshotDigest || !payload.projectSnapshot || !validAgentDiscoverySnapshot(payload.projectSnapshot) || payload.projectSnapshot.rootRealpath !== payload.projectTrust.discoveryRootRealpath || payload.projectSnapshot.digest !== payload.projectTrust.snapshotDigest)) || (!payload.projectTrust && (payload.projectSnapshot !== undefined || payload.projectRootRealpath !== undefined || payload.projectSnapshotDigest !== undefined))) throw new Error("call private payload binding cannot be proven"); return payload; }
export async function readDelegationPayload(rootDir: string, view: InternalView, delegation: InternalDelegation): Promise<CallPayload & { delegationId: string; slotIndex: number; requiredIdentity: string; callRequestDigest: string; normalizedRequestDigest: string; requestDigest: string; effectiveCwd: string; item: DispatchItemInput }> { const call = await callPayload(rootDir, view.call!); const d = dirs(rootDir); const payload = await readPrivate<Awaited<ReturnType<typeof readDelegationPayload>>>(privatePayload(d, delegation.privatePayloadRef.slice(8))); const accepted = view.events.filter((event) => event.type === "config_revision_accepted" && event.delegationId === delegation.delegationId).at(-1); const expectedRevisionValue = accepted ? await readPrivate<unknown>(privatePayload(d, String(accepted.data.revisionRef).slice("private:".length))) : undefined; if (accepted && (!revisionPrivateValidator || !revisionPrivateValidator(expectedRevisionValue, view.call!.dispatchCallId, delegation.delegationId))) throw new Error("config revision private state schema invalid"); const expectedRevision = expectedRevisionValue as any; const expectedNormalized = accepted && typeof accepted.data.requestDigest === "string" ? accepted.data.requestDigest : view.call!.requestDigest; const expectedRoot = expectedRevision?.projectRootRealpath ?? call.projectRootRealpath; const expectedSnapshot = expectedRevision?.projectSnapshotDigest ?? call.projectSnapshotDigest; const expectedItem = call.items[delegation.slotIndex]; const expectedCwd = path.resolve(expectedItem?.cwd ?? call.cwd); if (!expectedItem || JSON.stringify(payload.item) !== JSON.stringify(expectedItem) || payload.delegationId !== delegation.delegationId || payload.dispatchCallId !== view.call!.dispatchCallId || payload.slotIndex !== delegation.slotIndex || payload.requiredIdentity !== delegation.requiredIdentity || payload.callRequestDigest !== view.call!.requestDigest || payload.normalizedRequestDigest !== expectedNormalized || payload.requestDigest !== delegationPayloadDigest(payload) || !path.isAbsolute(payload.effectiveCwd) || payload.effectiveCwd !== expectedCwd || hashPath(payload.effectiveCwd) !== delegation.effectiveCwdHash || payload.item.agent !== delegation.requestedTarget || payload.projectRootRealpath !== expectedRoot || payload.projectSnapshotDigest !== expectedSnapshot || (expectedRoot !== undefined && (!payload.projectSnapshot || !validAgentDiscoverySnapshot(payload.projectSnapshot) || payload.projectSnapshot.rootRealpath !== expectedRoot || payload.projectSnapshot.digest !== expectedSnapshot)) || (expectedRoot === undefined && payload.projectSnapshot !== undefined) || payload.projectSnapshot?.digest !== (expectedRevision?.projectSnapshot?.digest ?? call.projectSnapshot?.digest)) throw new Error("delegation private payload binding cannot be proven"); return payload; }
export async function readCurrentDelegationPayload(rootDir: string, view: InternalView, delegation: InternalDelegation): Promise<Awaited<ReturnType<typeof readDelegationPayload>>> { const call = await callPayload(rootDir, view.call!); const d = dirs(rootDir); const payload = await readPrivate<Awaited<ReturnType<typeof readDelegationPayload>>>(privatePayload(d, delegation.privatePayloadRef.slice(8))); const expectedItem = call.items[delegation.slotIndex]; const hasProject = payload.projectRootRealpath !== undefined || payload.projectSnapshotDigest !== undefined || payload.projectSnapshot !== undefined; if (!expectedItem || JSON.stringify(payload.item) !== JSON.stringify(expectedItem) || payload.delegationId !== delegation.delegationId || payload.dispatchCallId !== view.call!.dispatchCallId || payload.slotIndex !== delegation.slotIndex || payload.requiredIdentity !== delegation.requiredIdentity || payload.callRequestDigest !== view.call!.requestDigest || !isHex(payload.normalizedRequestDigest) || payload.requestDigest !== delegationPayloadDigest(payload) || !path.isAbsolute(payload.effectiveCwd) || payload.effectiveCwd !== path.resolve(expectedItem.cwd ?? call.cwd) || hashPath(payload.effectiveCwd) !== delegation.effectiveCwdHash || payload.item.agent !== delegation.requestedTarget || (hasProject && (typeof payload.projectRootRealpath !== "string" || typeof payload.projectSnapshotDigest !== "string" || !validAgentDiscoverySnapshot(payload.projectSnapshot) || payload.projectSnapshot.rootRealpath !== payload.projectRootRealpath || payload.projectSnapshot.digest !== payload.projectSnapshotDigest)) || (!hasProject && payload.projectRootRealpath !== undefined)) throw new Error("current delegation private payload cannot be proven"); return payload; }
export { nodeFs, fs, path, getAgentDiscoverySnapshot, validAgentDiscoverySnapshot, lineageMatches, ownerFileSync, readStableOwnerFileSync };
