/** Internal foundation seam. The package root and package exports intentionally do not expose this module. */
export {
  admitDispatchCallInternal,
  resolveDelegationInternal,
  acceptConfigRevisionInternal,
  reserveInitialInternal,
  reserveRecoveryCycleInternal,
  claimExecutionOwnerInternal,
  executeReattachedDelegationInternal,
  acceptContinuationInternal,
  requestDelegationCancelInternal,
  requestDelegationCancelScopedInternal,
  reconcileDelegationCancelInternal,
  reconcileCancellationInternal,
  bindChildSessionInternal,
  reconcileRunningChildInternal,
  executeDelegationInternal,
  markSpawnStartedInternal,
  markDelegationReturnedInternal,
  admitNextChainStepInternal,
  finalizeCallInternal,
  readDispatchCallInternal,
  readDelegationInternal,
  normalizeStartupInternal,
  normalizeExecutionStartupInternal,
  reconcilePrivateOrphans,
  projectDispatchCall,
  classifyOwnerIdentityObservation,
  probeOwnerDeathStable,
  delegationFoundationCapability,
  SubagentControlService,
} from "./delegation.ts";
export type { CancelActor, CancelReceipt, CancelScope, ConfigRevisionActor, DelegationFoundationDependencies, DelegationExecutionDependencies, DelegationExecutionResult, ChildInspection, OrphanReconciliationResult, OwnerIdentity, OwnerIdentityObservation, OwnerLiveness } from "./delegation.ts";
export type { OwnerClaim, OwnerIdentityProbeSafetyAdapter } from "./execution-supervisor.ts";
